# Generated by Django 3.2.16 on 2022-11-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datats',
            name='enchufao',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
